# Generated by Django 3.2 on 2022-03-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=60, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=40)),
                ('year_published', models.CharField(blank=True, max_length=4)),
                ('synopsis', models.TextField(blank=True)),
                ('members_rating', models.PositiveSmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=16, unique=True)),
                ('meetup_date', models.DateTimeField()),
                ('details', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Finished'), (2, 'Cancelled')], default=0)),
                ('book1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book1', to='blog.book')),
                ('book2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book2', to='blog.book')),
            ],
        ),
    ]
