# Generated by Django 3.2 on 2022-03-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_meetup_book2'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='title',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
