# Generated by Django 3.2 on 2022-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', editable=False, max_length=200, unique=True),
        ),
    ]
