# Generated by Django 3.2 on 2022-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_meetup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
