# Generated by Django 3.2 on 2022-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=40, unique=True),
        ),
    ]
