# Generated by Django 3.2 on 2022-04-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220405_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(default='bound-method-fieldvalue_from_object-of-djangodbmodelsfieldscharfield', max_length=40, unique=True),
        ),
    ]
