# Generated by Django 3.2 on 2022-04-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_meetup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
